### ISSUE TITLE
Default `kwargs=None` cannot be unpacked

### ISSUE THREAD

**Issue by smcoll** [steinitzu/celery-singleton#2]
A task called without `kwargs` results in a `TypeError` because the `kwargs=None` default can't be unpacked with `**`.  For example:

```
mytask.apply_async(args=(1,), priority=3)
```

Here's the traceback:

```
Traceback (most recent call last):
[...]
  File "/usr/local/lib/python2.7/site-packages/celery_singleton/singleton.py", line 55, in apply_async
    lock = self.generate_lock(self.name, *args, **kwargs)
TypeError: generate_lock() argument after ** must be a mapping, not NoneType
```

It seems that `None` needs to be converted to an empty dictionary first.  Perhaps `args` would need to be converted as well.

**Comment by steinitzu** [comment]
Ah, thanks for catching that.
Replacing kwargs with an empty dict in apply_async would definitely be the
sane solution (and empty list for args).

**Comment by steinitzu** [comment]
Fixed https://github.com/steinitzu/celery-singleton/commit/de51918742761b77dc5702dc8b7dffa7a22496ee
