### ISSUE TITLE
Is singleton working for 'send_task' method?

### ISSUE THREAD

**Issue by Fan-Gong** [steinitzu/celery-singleton#24]
Hi,

Hope you are doing good.

I am using `send_task('task_name',args)` to send celery tasks. When define the celery task i also added the `base=singleton` parameter, but seems it is not working.

I saw from the doc we suggested to use `delay` or `apply_async` method but in my case I will need to use `send_task` method since it passes the task name. So do we really support `send_task` method?

Thanks,
Victor

**Comment by steinitzu** [comment]
That's unfortunately not possible with the current approach celery-singleton uses.  
`send_task` doesn't know or care what task class you're using.

All the locking logic happens in `Singleton.apply_async` which in turn calls `celery.Task.apply_async` which in turn calls `Celery.send_task` to send the task to the broker.

Calling `send_task` directly you skip all the locking logic and singleton can't do anything for you.

It's possible to support but it would be a very differnet apprach that involves extending the celery app itself to override `send_task`

**Comment by Fan-Gong** [comment]
Hi @steinitzu, thank you so much for your quick reply.

My current situation is that my celery tasks and the APIs used are under two different containers, in that case i can only use `send_task` function to call the task by name instead of directly import the task module and call by using `apply_async`

So with my limitation to only use `send_task` function, is there any suggestion you could give that i can modify by myself to achieve celery-singleton? 

Thanks!

**Comment by steinitzu** [comment]
I'd suggest taking a look at the `Singleton` source code https://github.com/steinitzu/celery-singleton/blob/master/celery_singleton/singleton.py#L78  how it overrides `apply_async`

I think you could copy most of it with only minor changes to create a custom `Celery` subclass and override `send_task` instead

You'd have to hook into [`on_success/failure`](https://github.com/steinitzu/celery-singleton/blob/master/celery_singleton/singleton.py#L145-L149) differently somehow to release the lock but there are signals and maybe other ways to achieve that.

**Comment by Fan-Gong** [comment]
Hi @steinitzu, thanks.

I have found a workaround which uses `signature("task_name").apply_async()` instead of `send_task`. However seems iy is still not working. Should this method be working fine for `celery-Singleton`?

Best,
Victor

**Comment by steinitzu** [comment]
No that can't work, as you said, your task is defined in a different container. If this could work you would also be able to do `my_task.apply_async(...)`

 `signature` just creates some ad-hoc `Task` like object afaik

**Comment by Fan-Gong** [comment]
Hi @steinitzu thank you so much. I changed my app structure and have managed to import the tasks directly. So now everything is working.


One typo I have found from the readme files under UNIQUE_ON section is:
`
@app.task(base=Singleton, **unique_on=['user_id', ]**)
def do_something(username, otherarg=None):
    time.sleep(5)


task1 = do_something.delay(username='bob', otherarg=99)
task2 = do_something.delay(username='bob', otherarg=100)  # this is a duplicate of task1
assert task1 == task2
`
I believe it should `unique_on=['username', ]` instead of `unique_on=['user_id', ]` right?

Thanks again for all your reply!

Best,
Vic

**Comment by steinitzu** [comment]
Glad it's working for you.
You're right, that is a typo :smile:
