### ISSUE TITLE
celery 5 compatibility release

### ISSUE THREAD

**Issue by wangsha** [steinitzu/celery-singleton#28]
I've tested on my project. celery 5 has no breaking changes. would love to have a new release that is celery-5 compatible. currently there is dependency conflicts.

**Comment by lifenautjoe** [comment]
Confirmed! 😢

**Comment by lifenautjoe** [comment]
@steinitzu Any chance of supporting celery 5.0? 

Issue seems to be with vine 

```
vine==1.3.0,==5.0.0
Tried: 0.9.0, 0.9.0, 0.9.1, 0.9.1, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 1.1.3, 1.1.3, 1.1.4, 1.1.4, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 5.0.0, 5.0.0

```

**Comment by kibernick** [comment]
Yes please, this prevents an upgrade of dependencies in pip-tools if both celery and celery-singleton are listed.

**Comment by steinitzu** [comment]
Should be no problem if there are no breaking changes.
We just need to sort out the dependencies in poetry and set up travis to test with both 4 and 5.

I'll get to this late next week probably, or if anybody wants to send a PR can get this in sooner.

**Comment by lifenautjoe** [comment]
Wohoooo!
