### ISSUE TITLE
Unable to use uuid object

### ISSUE THREAD

**Issue by venomone** [steinitzu/celery-singleton#36]
Hello,

since im using celery-singleton

Call Task:
`do_something = allocate_something.apply_async(kwargs={"user": user.pk})`

Task itself:
```

@app.task(name="Allocate something", base=Singleton, ignore_result=False)
def allocate_something(user):
    user = User.objects.get(pk=user)
```

I Always get back the following TypeError: Object of type UUID is not JSON serializable

Can smb help?

**Comment by yokotoka** [comment]
Use `str(user.pk` in kwargs

**Comment by steinitzu** [comment]
All arguments must be encodable with `json.dumps()`. This is needed to create a stable hash of the task signature.
You can convert your uuid to str in kwargs and back to uuid object inside the task.

**Comment by lewiseason** [comment]
For anyone coming across this now:
Alongside #42, which would probably be the neatest way to work around this that doesn't involve refactoring all of your call sites—I am using this temporarily in a project:

```python
class BaseSingletonTask(Singleton):
    def generate_lock(self, task_name, task_args=None, task_kwargs=None):
        task_args = task_args or []
        task_kwargs = task_kwargs or {}

        for index, arg in enumerate(task_args):
            if isinstance(arg, uuid.UUID):
                task_args[index] = str(arg)

        for key, value in task_kwargs.items():
            if isinstance(value, uuid.UUID):
                task_kwargs[key] = str(value)

        return super().generate_lock(task_name, task_args, task_kwargs)
```
