### ISSUE TITLE
AttributeError when get_existing_task_id runs for a lock which no longer exists

### ISSUE THREAD

**Issue by smcoll** [steinitzu/celery-singleton#4]
i think this is a race condition, which happens when a lock doesn't exist any longer.

```
django.request [ERROR] [exception:handle_uncaught_exception] Internal Server Error: /mypath
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  [...]
  File "/myapp/views.py", line 149, in my_view
    my_task.apply_async(args=(force_text(foo),), priority=9)
  File "/usr/local/lib/python3.5/site-packages/celery_singleton/singleton.py", line 69, in apply_async
    existing_task_id = self.get_existing_task_id(lock)
  File "/usr/local/lib/python3.5/site-packages/celery_singleton/singleton.py", line 26, in get_existing_task_id
    return app.backend.client.get(lock).decode()
AttributeError: 'NoneType' object has no attribute 'decode'
```

This could be a condition which only happens in my own implementation, which looks like this:
```
class MySingleton(Singleton):
    """ Implementation of the celery Singleton which leaves lock releasing to the task.
    """
    abstract = True

    def on_failure(self, *args, **kwargs):
        pass

    def on_success(self, *args, **kwargs):
        pass

@shared_task(ignore_result=True, bind=True, base=MySingleton)
def my_task(self, my_arg):
    self.release_lock(my_arg)
    # [...]
```

**Comment by steinitzu** [comment]
Oops, looks like you won the race condition lottery :1st_place_medal: 

It's fixed now in: https://github.com/steinitzu/celery-singleton/commit/d5896083c612f10fa1b7e48989da57808bf75a2e
I'll get it up on pypi asap. 
Missing `None` check pretty much.

I already had a retry loop in place to handle exactly this case of lock being released right after a failed attempt to run a duplicate (it can happen with the standard `Singleton` as well):  
https://github.com/steinitzu/celery-singleton/blob/master/celery_singleton/singleton.py#L71  
But it always would have failed with this small oversight. :/

**Comment by smcoll** [comment]
@steinitzu thanks for that quick work!

**Comment by steinitzu** [comment]
You're welcome @smcoll , thanks for letting me know!
