### ISSUE TITLE
Celery will delete SINGLETONLOCK key when running task

### ISSUE THREAD

**Issue by Daocheng** [steinitzu/celery-singleton#6]
Environment:
celery==4.1.0
celery-singleton==0.1.3
redis==2.10.6

Celery will delete SINGLETONLOCK key when running task, adding a 'celery' prefix to the key will fix the issue.
I think using a separate redis backend will be better.

**Comment by steinitzu** [comment]
Hey, reopening this to remind me to make the key prefix and redis server URL configurable.
